import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Wings of Freedom",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2022/09/aot_tiedye_comicsense.jpg",
    price: "849",
    categoryName: "oversize",
  },
  {
    _id: uuid(),
    title: "Inosuke Beast",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2023/03/demonslayer_innosuke_beastbreathing_secondfang_oversizetee_back_listing_hitanshi_comicsense.jpg",
    price: "900",
    categoryName: "oversize",
  },
  {
    _id: uuid(),
    title: "Denji's Dream",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2023/03/dreams_denji2_comicsense.jpg",
    price: "949",
    categoryName: "oversize",
  },
  {
    _id: uuid(),
    title: "Black Dragon",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2023/05/tokyorevengers_blackdragon_fullsleevetee_listing3_hitanshi-800x1067.jpg",
    price: "899",
    categoryName: "oversize",
  },
  {
    _id: uuid(),
    title: "Anya",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2022/06/anya_oversize_white_ha_comicsense.jpg",
    price: "849",
    categoryName: "oversize",
  },
  {
    _id: uuid(),
    title: "AOT Jacket",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2021/03/aot_bomber_front_comicsense.jpg",
    price: "1300",
    categoryName: "winterWear",
  },
  {
    _id: uuid(),
    title: "Draken Jacket",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2021/11/draken_bomber_compressed.jpg",
    price: "1400",
    categoryName: "winterWear",
  },
  {
    _id: uuid(),
    title: "One Piece",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2021/03/one_piece_pirates_bomberjacket_comicsense.jpg",
    price: "1400",
    categoryName: "winterWear",
  },
  {
    _id: uuid(),
    title: "Itadori Uniform",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2021/09/itadori_cosplay_hoodief_comicsense.jpg",
    price: "1400",
    categoryName: "winterWear",
  },
  {
    _id: uuid(),
    title: "Akatsuki",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2021/03/akatsuki_hoodie_front_comicsense.jpg",
    price: "1500",
    categoryName: "winterWear",
  },
  {
    _id: uuid(),
    title: "Zenitsu",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2022/08/closeups7_comicsense.jpg",
    price: "2299",
    categoryName: "figurine",
  },
  {
    _id: uuid(),
    title: "Monkey D Luffy",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2023/03/bp192805_comicsense.jpg",
    price: "2299",
    categoryName: "figurine",
  },
  {
    _id: uuid(),
    title: "Takemichi Hanagaki",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2022/08/takemichi5_comicsense-1.jpg",
    price: "1999",
    categoryName: "figurine",
  },
  {
    _id: uuid(),
    title: "L",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2022/08/L_SFC_comicsense-1.jpg",
    price: "3200",
    categoryName: "figurine",
  },
  {
    _id: uuid(),
    title: "Izuju Midoriya",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2022/11/deku_comicsense.jpg",
    price: "7999",
    categoryName: "figurine",
  },
  {
    _id: uuid(),
    title: "Jolyne Cujoh",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2023/03/bp191365_comicsense.jpg",
    price: "2299",
    categoryName: "figurine",
  },
  {
    _id: uuid(),
    title: "Strawhats Logo",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2021/03/luffy_logo_comicsense.jpg",
    price: "59",
    categoryName: "stickers",
  },
  {
    _id: uuid(),
    title: "Zenitsu's Dream",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2022/02/zenitsu-dream_mock_comicsense-1.jpg",
    price: "59",
    categoryName: "stickers",
  },
  {
    _id: uuid(),
    title: "Chika Sticker",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2021/12/chika_mock_comicsense.jpg",
    price: "59",
    categoryName: "stickers",
  },
  {
    _id: uuid(),
    title: "PLUS ULTRA",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2021/03/plusultra_comicsense.jpg",
    price: "59",
    categoryName: "stickers",
  },
  {
    _id: uuid(),
    title: "Kakashi's Sharingan",
    img:"https://comicsense.b-cdn.net/wp-content/uploads/2021/03/kakashi_sharingan_comicsense.jpg",
    price: "59",
    categoryName: "stickers",
  },
];
